---
- hosts: all
  gather_facts: no

  vars_prompt:
    - name: "branch"
      prompt: "branch"
      private: no

  environment:
    AWS_PROFILE: "{{ aws_profile }}"

  tasks:
    - include_tasks: release-tasks.yml
